
package net.restfulwebservices.servicecontracts._2008._01;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import net.restfulwebservices.datacontracts._2008._01.GeoLocation;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IGeoIPService", targetNamespace = "http://www.restfulwebservices.net/ServiceContracts/2008/01")
@XmlSeeAlso({
    com.microsoft.schemas._2003._10.serialization.ObjectFactory.class,
    faultcontracts.gotlservices._2008._01.ObjectFactory.class,
    net.restfulwebservices.datacontracts._2008._01.ObjectFactory.class,
    net.restfulwebservices.servicecontracts._2008._01.ObjectFactory.class
})
public interface IGeoIPService {


    /**
     * 
     * @param request
     * @return
     *     returns net.restfulwebservices.datacontracts._2008._01.GeoLocation
     * @throws IGeoIPServiceAnalyseDefaultFaultContractFaultFaultMessage
     */
    @WebMethod(operationName = "Analyse", action = "Analyse")
    @WebResult(name = "AnalyseResult", targetNamespace = "http://www.restfulwebservices.net/ServiceContracts/2008/01")
    @RequestWrapper(localName = "Analyse", targetNamespace = "http://www.restfulwebservices.net/ServiceContracts/2008/01", className = "net.restfulwebservices.servicecontracts._2008._01.Analyse")
    @ResponseWrapper(localName = "AnalyseResponse", targetNamespace = "http://www.restfulwebservices.net/ServiceContracts/2008/01", className = "net.restfulwebservices.servicecontracts._2008._01.AnalyseResponse")
    public GeoLocation analyse(
        @WebParam(name = "request", targetNamespace = "http://www.restfulwebservices.net/ServiceContracts/2008/01")
        String request)
        throws IGeoIPServiceAnalyseDefaultFaultContractFaultFaultMessage
    ;

}
